spring:
  application:
    name: DingZhenServlet
  datasource:
    url: jdbc:h2:file:./dingzhen
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
share:
  cold-down:
    # 公共冷却
    global:
      enabled: false
      # 持续时间,取随机数 单位minutes
      during-min: 3
      during-max: 5
      # 持续时间 单位minutes
    # 每个账户的冷却
    pre-account:
      during-min: 3
      during-max: 5
    queue:
      # 是否启用额外的排队机制
      state: true
  crypt:
    # AES Key
    # 用于加密一些数据,实际部署请修改这个
    secret-key: powered-by-zzyss
service:
  # 服务端工作模式
  # full 可以刷新VapeToken 也可以作为验证服务 默认使用gateway
  # gateway 当作vape gateway服务端, 专门用来刷新Vape token用
  # local-only 仅在本地处理账户,不走任何gateway
  mode: full
  gateway:
    # Gateway是一个用户绕过CF速率检测的服务,如果你的用户/共享号子过多可以尝试使用

    # 安全设定: 是否在验证服务开启的时候也启用gateway服务
    # 建议保持关闭,否则可能会被偷token
    # 注意: 即使mode设置为local-only也会开启gateway, 这两个服务是互不干扰的
    always: false
    # gateway 验证密钥
    # 请务必修改这个值,否则token会被盗刷
    key: zzyss-please-modify-this