spring:
  application:
    name: DingZhenServlet
  datasource:
    url: jdbc:h2:file:./dingzhen.db
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true

  cloud:
    gateway:
      mvc:
        routes:
          - id: api_route
            uri: https://online.vape.gg/api
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/(?<path>.*), /${path}
  jpa:
    hibernate:
      ddl-auto: update