spring:
  application:
    name: DingZhenServlet
  cloud:
    gateway:
      mvc:
        routes:
          - id: api_route
            uri: https://online.vape.gg/api
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/(?<path>.*), /${path}

