spring:
  application:
    name: DingZhenServlet
  data:
    mongodb:
      # 数据库地址,如果gateway和主控搭建在同一个服务器上建议修改
      uri: mongodb://localhost:27017/vape-share
# 数据库加密
# 实际部署的时候请务必修改这个,否则他人可能可以解密你的数据库
# openssl rand -base64 32
mongodb.encrypt:
  keys:
    - version: 1
      key: R0afdUePq5uuN+Lnm8MFb5jGQFRsAi3wuMv3QE41YrE=
share:
  # Token刷新服务器设置
  issuer:
    # 服务端内www.vape.gg解析的IP
    # 不是本地搭建保留默认即可 (auto)
    # 本地搭建请填写一个你本地可以访问的Cloudflare节点, 例如 172.67.41.38
    ip: auto
  # 云配设置
  online:
    # 公共配置搜索
    search:
      # 是否启用搜索,设置为false则不会展示任何搜索结果
      state: true
      # 每页大小,设置太大可能导致客户端响应缓慢
      page-size: 24
  webhook:
    # 是否启用webhook
    state: true
  cold-down:
    # 公共冷却
    global:
      enabled: false
      # 持续时间,取随机数 单位minutes
      during-min: 3
      during-max: 5
      # 持续时间 单位minutes
    # 每个账户的冷却
    pre-account:
      during-min: 3
      during-max: 5
    queue:
      # 是否启用额外的排队机制
      state: true
  user:
    # 每日自动清理失效用户
    auto-delete-expired: true
  maintain:
    # 是否在维护结束后自动补偿时间
    auto-renew: true
service:
  # 服务端工作模式
  # full 可以刷新VapeToken 也可以作为验证服务 默认使用gateway
  # gateway 当作vape gateway服务端, 专门用来刷新Vape token用
  # local-only 仅在本地处理账户,不走任何gateway
  mode: full
  gateway:
    # Gateway是一个用户绕过CF速率检测的服务,如果你的用户/共享号子过多可以尝试使用

    # 安全设定: 是否在验证服务开启的时候也启用gateway服务
    # 建议保持关闭,否则可能会被偷token
    # 注意: 即使mode设置为local-only也会开启gateway, 这两个服务是互不干扰的
    always: false
    # gateway 加密密钥
    # 会用于验证连接和传递token 加密算法AES-256
    # 如果你要部署密钥刷新服务, 请务必修改这个值,否则token会被盗刷
    # openssl rand -base64 32
    key: tg8DRuZZc9rAxrQgqDx/IuTa0ZgDogZ1cIxAO1udGPg=
    # 心跳包设置 (主控)
    heartbeat:
      # 是否发送心跳包 (主控)
      state: true
