name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: "gradle"
      #            - name: Set outputs
      #              id: vars
      #              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: chmod +x ./gradlew  && ./gradlew bootJar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DingZhen
          path: build/libs/DingZhenServlet-*.jar